version: "3.9"

services:
  db:
    image: postgres:15
    container_name: mechanic_db
    restart: always
    environment:
      POSTGRES_DB: mechanic_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: mechanic_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mechanic_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - .:/app

volumes:
  postgres_data: